

<div class="row">

    <div class="col-md-4">
        
    </div>

    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"><?php echo $this->translate('Login help') ?></h3>
            </div>
            <div class="panel-body">
                <div class="error">
                    <?php
                   echo $errorMessage;
                   echo $successMessage;
                    ?>
                </div>
               <?php
              echo $this->form()->openTag($form);
              echo $this->formCollection($form);
              echo $this->form()->closeTag();
               ?>
            </div>
        </div>
    </div>

    <div class="col-md-4">
       
    </div>
</div>
